config/routes.rb
Rails.application.routes.draw do
  resources :songs
  get 'pages/home'
  root :to => 'pages#home'

end

app/models/song.rb
class Song < ActiveRecord::Base
	default_scope { order('year ASC, rank ASC')}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:year, :rank, :artist, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navigation_helper.rb
#---
# Excerpted from "The Rails View",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/warv for more book information.
#---
module NavigationHelper

  def nav_tab(title, url, options = {})
    current_tab = options.delete(:current)
    options[:class] = (current_tab == title) ? 'active' : 'inactive'
    content_tag(:li, link_to(title, url), options)
  end

  def currently_at(tab)
    render partial: 'layouts/main_nav', locals: {current_tab: tab}
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/_footer.html.erb
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2013 Santi Soontarinka All Rights Reserved. All Wrongs Reversed.</p>
  </footer>

app/views/layouts/_header.html.erb
<header id="page_header" role="banner">

<%= link_to(
image_tag("logo.png",
alt: "Artflow",
id: "logo"),
title: "Dashboard") %>
<%= yield :main_navigation %>	




</header>

app/views/layouts/_main_nav.html.erb
<% content_for :main_navigation do %>
  <nav id="main_nav" role="navigation">
    <ul>

      <%= nav_tab 'Home',    root_path,    current: current_tab %>    
      <%= nav_tab 'Songs', songs_path, current: current_tab %>
           
    </ul>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
    <% if content_for?(:title) %>
      Music: <%= yield :title %>
    <% else %>
      Music
    <% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
<%= image_tag("tagline.png", alt: "Lyric", id: "tagline") %>
  <div class="container">
    <section id="content">
      <%# START:notifications %>
      <% if notice %>
        <p class="notification notice">
          <%= notice %>
        </p>
      <% end %>

      <% if alert %>
        <p class="notification alert">
          <%= alert %>
        </p>
      <% end %>
      <%# END:notifications %>
      <%= yield %>
    </section>
    
    <section id="sidebar">
      <nav id="functional_nav">      	
        <ul>

          <%= yield :functional_nav %>
        </ul>
      </nav>
      <%= yield :sidebar %>
      <section id="recent_activity">
        <header><h1 class="ir" id="recent">Recent Activity</h1></header>
    <%#    <%= render partial: 'activity_items/recent' %>
      </section>
    </section>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<% currently_at 'Home' %>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<% content_for :functional_nav do%>
<li><%= link_to 'Add', new_song_path %></li>
<% end %>
<%= currently_at 'Songs'%>


<h1>Listing Songs</h1>

<table id="songs" class="display">

  <thead>
    <tr>
      <th>Year</th>
      <th>Rank</th>
      <th>Artist</th>
      <th>Name</th>
      <th>Artis_Song</th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.year %></td>
        <td><%= link_to(song.rank, song) %></td>
        <td><%= song.artist %></td>
        <td><%= song.name %></td>
        <td><%= song.artist.downcase + " - " + song.name.downcase + " hd" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<% content_for :functional_nav do%>
<li><%= link_to 'Add', new_song_path %></li>
<li><%= link_to 'Edit', edit_song_path(@song) %></li>
<li><%= link_to 'Back', songs_path %></li>
<% end %>
<%= currently_at 'Songs'%>


<p>
  <strong>Year:</strong>
  <%= @song.year %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @song.rank %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>